### PR TITLE
autorotate-iio: Track core changes

### LINKED ISSUE #4: Build error with latest commit
```shell
../src/autorotate-iio.cpp:75:5: error: could not convert ‘<lambda closure object>WayfireAutorotateIIO::<lambda(wf_activator_source, int32_t)>{((WayfireAutorotateIIO*)this)}’ from ‘WayfireAutorotateIIO::<lambda(wf_activator_source, int32_t)>’ to ‘activator_callback’ {aka ‘std::function<bool(wf_activator_source, unsigned int)>’}
   75 |     };
      |     ^
      |     |
      |     WayfireAutorotateIIO::<lambda(wf_activator_source, int32_t)>
../src/autorotate-iio.cpp:78:5: error: could not convert ‘<lambda closure object>WayfireAutorotateIIO::<lambda(wf_activator_source, int32_t)>{((WayfireAutorotateIIO*)this)}’ from ‘WayfireAutorotateIIO::<lambda(wf_activator_source, int32_t)>’ to ‘activator_callback’ {aka ‘std::function<bool(wf_activator_source, unsigned int)>’}
   78 |     };
      |     ^
      |     |
      |     WayfireAutorotateIIO::<lambda(wf_activator_source, int32_t)>
../src/autorotate-iio.cpp:81:5: error: could not convert ‘<lambda closure object>WayfireAutorotateIIO::<lambda(wf_activator_source, int32_t)>{((WayfireAutorotateIIO*)this)}’ from ‘WayfireAutorotateIIO::<lambda(wf_activator_source, int32_t)>’ to ‘activator_callback’ {aka ‘std::function<bool(wf_activator_source, unsigned int)>’}
   81 |     };
      |     ^
      |     |
      |     WayfireAutorotateIIO::<lambda(wf_activator_source, int32_t)>
../src/autorotate-iio.cpp:84:5: error: could not convert ‘<lambda closure object>WayfireAutorotateIIO::<lambda(wf_activator_source, int32_t)>{((WayfireAutorotateIIO*)this)}’ from ‘WayfireAutorotateIIO::<lambda(wf_activator_source, int32_t)>’ to ‘activator_callback’ {aka ‘std::function<bool(wf_activator_source, unsigned int)>’}
   84 |     };
      |     ^
      |     |
      |     WayfireAutorotateIIO::<lambda(wf_activator_source, int32_t)>
```

### PR DESCRIPTION
**Pull request by soreau**
Returns bool for bindings, changed in wayfire c71d548.
Fixes #4.

### CODE REVIEW

File: src/autorotate-iio.cpp [hunk 1]
```diff
@@ -71,16 +71,24 @@ class WayfireAutorotateIIO : public wf::plugin_interface_t
...
     };
     activator_callback on_rotate_up = [=] (wf_activator_source src, int32_t) {
-        on_rotate_binding(WL_OUTPUT_TRANSFORM_NORMAL);
+        if (!output->can_activate_plugin(grab_interface))
+            return false;
+        return on_rotate_binding(WL_OUTPUT_TRANSFORM_NORMAL);
     };
     activator_callback on_rotate_down = [=] (wf_activator_source src, int32_t) {
-        on_rotate_binding(WL_OUTPUT_TRANSFORM_180);
+        if (!output->can_activate_plugin(grab_interface))
```
Comment (ammen99) [inline src/autorotate-iio.cpp]: I'd move this check in `on_rotate_binding`, this way you don't need to write it each time.

Comment (soreau) [reply src/autorotate-iio.cpp]: I don't understand what you're saying. AFAIU, it needs this so a binding bound to this will still work in wcm keybinding grabs.

Comment (ammen99) [reply src/autorotate-iio.cpp]: What I mean is that you are doing the same thing in all callbacks: `if (!can_activate) return false; else return on_rotate_binding()` Instead, you can have the `if(!can_activate)` check inside `on_rotate_binding()` (and this way you don't have to type `if (!can_activate)` each time).

Comment (soreau) [reply src/autorotate-iio.cpp]: Ah, I see what you mean.

**Comment by ammen99** [comment]
Thanks!
